"""Bake the CC0 Xelu Light PNGs into the native prompt header.

Run manually after changing the art (requires Pillow). Normal C++ builds use
the checked-in header and need no image library or loose files at runtime.
"""
import argparse
import hashlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/input-prompts/xelu-light"
OUTPUT = ROOT / "renderer/engine/xelu_light.generated.h"
SIZE = 32


def stamp(canvas, key, box):
    with Image.open(SOURCE / f"{key}_Key_Light.png") as source:
        rgba = source.convert("RGBA")
    # Remove the pack's export padding, retaining the authored shadow/alpha.
    rgba = rgba.crop(rgba.getbbox())
    x, y, w, h = box
    fitted = ImageOps.contain(rgba, (w, h), Image.Resampling.LANCZOS)
    canvas.alpha_composite(fitted, (x + (w - fitted.width) // 2,
                                    y + (h - fitted.height) // 2))


def compose(*placements):
    canvas = Image.new("RGBA", (SIZE, SIZE))
    for key, box in placements:
        stamp(canvas, key, box)
    return canvas


def pair(top, bottom):
    return compose((top, (1, 0, 30, 15)), (bottom, (1, 17, 30, 15)))


def wasd(canvas, box):
    x, y, w, h = box
    cell_w, cell_h = w // 3, h // 2
    for key, col, row in (("W", 1, 0), ("A", 0, 1), ("S", 1, 1), ("D", 2, 1)):
        stamp(canvas, key, (x + col * cell_w, y + row * cell_h, cell_w, cell_h))


def sprites():
    art = {}
    for label, key in {
        "E": "E", "F": "F", "Q": "Q", "G": "G", "Spc": "Space",
        "Ent": "Enter", "Tab": "Tab", "Ct": "Ctrl", "?": "Question",
        "LMB": "Mouse_Left", "RMB": "Mouse_Right", "MMB": "Mouse_Middle",
        "Mse": "Mouse_Simple",
    }.items():
        art[label] = compose((key, (1, 1, 30, 30)))
    for label, top, bottom in (
        ("R/Esc", "R", "Esc"), ("Sh/MMB", "Shift", "Mouse_Middle"),
        ("1/<", "1", "Arrow_Left"), ("2/>", "2", "Arrow_Right"),
        ("3/^", "3", "Arrow_Up"), ("4/v", "4", "Arrow_Down"),
        ("3/4", "3", "4"), ("1/2", "1", "2"), ("Ct/Sh", "Ctrl", "Shift"),
    ):
        art[label] = pair(top, bottom)
    art["WASD"] = compose()
    wasd(art["WASD"], (1, 3, 30, 26))
    art["WASD/Mse"] = compose(("Mouse_Simple", (21, 5, 11, 23)))
    wasd(art["WASD/Mse"], (0, 7, 21, 18))
    # Xelu's middle highlight also marks the wheel. Its authored arrow keycaps
    # distinguish scrolling from a wheel click; no substitute font is drawn.
    art["Wheel"] = compose(("Mouse_Middle", (0, 1, 21, 30)),
                            ("Arrow_Up", (22, 3, 10, 11)),
                            ("Arrow_Down", (22, 18, 10, 11)))
    return art


def generate(art):
    lines = ["// Generated by tools/compile_prompt_icons.py; do not edit.",
             "// Xelu Light by Nicolae (Xelu) Berbece, CC0.",
             "// https://thoseawesomeguys.com/prompts/",
             "#pragma once", "#include <cstdint>", "#include <string_view>",
             "namespace DarkRecomp::Prompts::XeluLight {"]
    for path in sorted(SOURCE.glob("*.png")):
        lines.append(f"// {path.name}: {hashlib.sha256(path.read_bytes()).hexdigest()}")
    for i, (label, picture) in enumerate(art.items()):
        data = picture.tobytes()
        values = [int.from_bytes(data[j:j + 4], "little") for j in range(0, len(data), 4)]
        lines.append(f"inline constexpr uint32_t kPixels{i}[1024] = {{ // {label}")
        for j in range(0, len(values), 8):
            lines.append("    " + ",".join(f"0x{v:08X}" for v in values[j:j + 8]) + ",")
        lines.append("};")
    lines.extend(["struct Sprite { std::string_view label; const uint32_t* rgba; };",
                  "inline constexpr Sprite kSprites[] = {"])
    for i, label in enumerate(art):
        lines.append(f'    {{"{label}", kPixels{i}}},')
    lines.extend(["};", "} // namespace DarkRecomp::Prompts::XeluLight", ""])
    return "\n".join(lines)


def preview(art, path):
    # Show exact 32px sprites beside a nearest-neighbor enlargement for review.
    sheet = Image.new("RGB", (600, ((len(art) + 5) // 6) * 150), (35, 38, 40))
    draw = ImageDraw.Draw(sheet)
    for i, (label, picture) in enumerate(art.items()):
        x, y = (i % 6) * 100, (i // 6) * 150
        sheet.paste(picture, (x + 34, y + 4), picture)
        zoom = picture.resize((80, 80), Image.Resampling.NEAREST)
        sheet.paste(zoom, (x + 10, y + 43), zoom)
        draw.text((x + 7, y + 130), label, fill="white")
    path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the checked-in header")
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()
    art = sprites()
    text = generate(art)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != text:
            raise SystemExit("Xelu Light header is stale; regenerate it.")
    else:
        OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    if args.preview:
        preview(art, args.preview)
    print(f"{'Verified' if args.check else 'Generated'} {len(art)} Xelu Light sprites.")


if __name__ == "__main__":
    main()
